---
- name: "Add profile.d files"
  become: true
  become_user: root
  ansible.builtin.copy:
    src: profile.d/
    dest: /etc/profile.d/
    mode: "644"

- name: "Set hostname"
  become: true
  become_user: root
  ansible.builtin.hostname:
    name: "{{inventory_hostname}}"

- name: "Add Vagant user to Docker group"
  become: true
  become_user: root
  ansible.builtin.user:
    name: vagrant
    groups:
      - docker

- ansible.builtin.stat:
    path: /usr/local/bin/go/bin/go
  register: go_exe

- name: "Install Golang"
  become: true
  become_user: root
  ansible.builtin.unarchive:
    remote_src: true
    src: https://golang.org/dl/go1.17.1.linux-amd64.tar.gz
    dest: /usr/local/bin
    validate_certs: false
  when: go_exe.stat.exists == false

- name: "Install development packages"
  become: true
  become_user: root
  ansible.builtin.apt:
    update_cache: true
    name:
      - make
      - build-essential

- name: "Reset SSH connection for Vagrant group membership to take effect"
  ansible.builtin.meta: reset_connection
