---
- name: "Add profile.d files"
  become: true
  become_user: root
  ansible.builtin.copy:
    src: profile.d/
    dest: /etc/profile.d/
    mode: "644"

- name: "Set hostname"
  become: true
  become_user: root
  ansible.builtin.hostname:
    name: "{{inventory_hostname}}"

- name: "Add Vagant user to Docker group"
  become: true
  become_user: root
  ansible.builtin.user:
    name: vagrant
    groups:
      - docker

- name: "Install Pack PPA"
  become: true
  become_user: root
  ansible.builtin.apt_repository:
    repo: "ppa:cncf-buildpacks/pack-cli"

- name: "Install Pack CLI"
  become: true
  become_user: root
  ansible.builtin.apt:
    update_cache: true
    name: pack-cli