---
- hosts: all
  tasks:
    - become: true
      become_user: root
      ansible.builtin.apt:
        update_cache: true
        name: zip

    - ansible.builtin.file:
        state: directory
        path: /vagrant/bin

    - ansible.builtin.stat:
        path: /vagrant/bin/nomad
      register: nomad_exe

    - name: "Download Nomad"
      ansible.builtin.unarchive:
        remote_src: true
        src: https://releases.hashicorp.com/nomad/1.1.2/nomad_1.1.2_linux_amd64.zip
        dest: /vagrant/bin/
      when: nomad_exe.stat.exists == false

    - ansible.builtin.stat:
        path: /vagrant/bin/consul
      register: consul_exe

    - name: "Download Consul"
      ansible.builtin.unarchive:
        remote_src: true
        src: https://releases.hashicorp.com/consul/1.10.2/consul_1.10.2_linux_amd64.zip
        dest: /vagrant/bin/
      when: consul_exe.stat.exists == false

- hosts: all
  roles:
    - docker
    - vagrant-user

- hosts: consul_servers
  roles:
    - role: consul
      vars:
        listen_ip: "{{ hostvars[inventory_hostname].private_ip }}"
        type: server
        num_servers: "{{ groups['consul_servers'] | length }}"
        server_ips: "{{ hostvars | json_query('*.private_ip') }}"
    
- hosts: nomad_servers
  roles: 
    - role: nomad
      vars:
        listen_ip: "{{ hostvars[inventory_hostname].private_ip }}"
        type: server
        num_servers: "{{ groups['nomad_servers'] | length }}"
        server_ips: "{{ hostvars | json_query('*.private_ip') }}"

- hosts: nomad_clients
  roles:
    - role: nomad
      vars:
        listen_ip: "{{ hostvars[inventory_hostname].private_ip }}"
        type: client
        num_servers: "{{ groups['nomad_servers'] | length }}"
        server_ips: "{{ hostvars | json_query('*.private_ip') }}"