---
- name: "Create Postgres directories"
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
  loop:
    - "/opt/postgres"
    - "/opt/postgres/data"
    - "/opt/postgres/data/{{service_name}}"

- become: true
  become_user: root
  ansible.builtin.apt:
    name: python3-pip
    update_cache: true

- ansible.builtin.pip:
    name: docker

- name: "Run Postgres container"
  community.docker.docker_container:
    name: "postgres-{{service_name}}"
    image: "postgres:13"
    network_mode: host
    volumes:
      - "/opt/postgres/data/{{service_name}}:/var/lib/postgresql/data"
    restart_policy: always
    env:
      POSTGRES_USER: "{{db_user}}"
      POSTGRES_PASSWORD: "{{db_password}}"
      POSTGRES_DB: "{{db_name}}"
