// <auto-generated />
namespace Api.Domain.Persistence.Migrations

open System
open Api.Domain.Persistence
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<Context>)>]
[<Migration("20211020183403_Applications")>]
type Applications() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Apps"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<Guid>(
                        nullable = false
                        ,``type`` = "uuid"
                    )
                Name =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "text"
                    )
                Version =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "integer"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Apps", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "Apps"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityByDefaultColumns().HasAnnotation("Relational:MaxIdentifierLength", 63)
            .HasAnnotation("ProductVersion", "5.0.11")
            |> ignore

        modelBuilder.Entity("Api.Domain.Applications.Application", (fun b ->

            b.Property<Guid>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid") |> ignore
            b.Property<string>("Name")
                .IsRequired(false)
                .HasColumnType("text") |> ignore
            b.Property<int>("Version")
                .IsRequired(true)
                .HasColumnType("integer") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Apps") |> ignore

        )) |> ignore

