// <auto-generated />
namespace Api.Domain.Persistence.Migrations

open System
open Api.Domain.Persistence
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Npgsql.EntityFrameworkCore.PostgreSQL.Metadata

[<DbContext(typeof<Context>)>]
type ContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityByDefaultColumns().HasAnnotation("Relational:MaxIdentifierLength", 63)
            .HasAnnotation("ProductVersion", "5.0.11")
            |> ignore

        modelBuilder.Entity("Api.Domain.Applications.Application", (fun b ->

            b.Property<Guid>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid") |> ignore
            b.Property<string>("Name")
                .IsRequired(false)
                .HasColumnType("text") |> ignore
            b.Property<int>("Version")
                .IsRequired(true)
                .HasColumnType("integer") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Apps") |> ignore

        )) |> ignore

