---
- name: "Create resolved.conf.d/"
  become: true
  become_user: root
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/resolved.conf.d


- name: "Insert Consul config for systemd-resolved"
  become: true
  become_user: root
  ansible.builtin.copy:
    content: |
      [Resolve]
      DNS=127.0.0.1
      DNSSEC=false
      Domains=~apps.internal ~paas.dev
    dest: /etc/systemd/resolved.conf.d/consul.conf

- name: "Stop systemd-resolved"
  become: true
  become_user: root
  ansible.builtin.systemd:
    daemon_reload: true
    name: systemd-resolved
    state: restarted   